[general]
import = [
    # "~/.config/alacritty/themes/themes/gruvbox_material_medium_light.toml",
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml",
]

[window]
opacity = 0.6
blur = true

[terminal]
shell = { program = "zj" }

[font]
size = 16.5
