shell zj

# forward to zellij
map ctrl+shift+t

font_size 16.5

background_opacity 0.75

# 果冻光标
cursor_trail 1
cursor_trail_decay 0.05 0.18
cursor_trail_start_threshold 2

include gruvbox-material-dark.conf
