## which filter mode to use
## possible values: global, host, session, directory
filter_mode = "directory"

## Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit.
# This applies for new installs. Old installs will keep the old behaviour unless configured otherwise.
enter_accept = true

[stats]

[keys]

[sync]
records = true

[preview]

[daemon]
