[helpers]

[shell.files]
shell = "~/.config/shell"
navi = "~/.local/share/navi/cheats"
memo = "~/.local/share/memo"
"starship.toml" = "~/.config/starship.toml"

[zsh]
depends = ["shell"]
[zsh.files]
zshrc = "~/.zshrc"
zimrc = { target = "~/.zimrc", type = "symbolic" }
zsh = { target = "~/.config/zsh", type = "symbolic" }

[bash]
depends = ["shell"]
files = { bashrc = "~/.bashrc" }

[fish]
depends = ["shell"]
files = { fish = "~/.config/fish" }

[nushell]
files = { nushell = "~/.config/nushell" }

[desktop.files]
rofi = "~/.config/rofi"
"mimeapps.list" = "~/.config/mimeapps.list"
applications = "~/.local/share/applications"

[X]
depends = ["desktop"]
[X.files]
xprofile = "~/.xprofile"
awesome = { target = "~/.config/awesome", type = "symbolic" }

[wayland]
depends = ["desktop"]
[wayland.files]
hypr = "~/.config/hypr"
swaylock = "~/.config/swaylock"
"waybar/config.jsonc" = "~/.config/waybar/config"
"waybar/style.css" = "~/.config/waybar/style.css"
plasma-workspace = "~/.config/plasma-workspace"

[vim.files]
LazyVim = { target = "~/.config/LazyVim", type = "symbolic" }
neovide = "~/.config/neovide"

[scripts.files]
bin = "~/.local/bin"

[terminal.files]
wezterm = "~/.config/wezterm"
zellij = "~/.config/zellij"
yazi = { target = "~/.config/yazi", type = "symbolic" }

[git.files]
git = "~/.config/git"
git-cliff = { target = "~/.config/git-cliff", type = "symbolic" }
gitui = "~/.config/gitui"

[media.files]
zathura = "~/.config/zathura"
mpv = "~/.config/mpv"

[templates.files]
Templates = { target = "~/Templates", type = "symbolic" }

[PL.files]
cargo = "~/.cargo"
gdb = "~/.config/gdb"
"pip.conf" = "~/.config/pip/pip.conf"

[monitor.files]
macchina = "~/.config/macchina"
