[helpers]

[shell.files]
navi = "~/.local/share/navi/cheats"
memo = "~/.local/share/memo"
"starship.toml" = "~/.config/starship.toml"

[zsh]
depends = ["shell"]
[zsh.files]
"zsh/zshenv" = "~/.zshenv"
"zsh/zshrc" = "~/.config/zsh/.zshrc"
"zsh/p10k.zsh" = "~/.config/zsh/p10k.zsh"

[fish]
depends = ["shell"]
files = { fish = "~/.config/fish" }

[nushell]
files = { nushell = "~/.config/nushell" }

[desktop.files]
rofi = "~/.config/rofi"
"mimeapps.list" = "~/.config/mimeapps.list"
applications = "~/.local/share/applications"

[X]
depends = ["desktop"]
[X.files]
awesome = { target = "~/.config/awesome", type = "symbolic" }

[wayland]
depends = ["desktop"]
[wayland.files]
hypr = "~/.config/hypr"
swaylock = "~/.config/swaylock"
"waybar/config.jsonc" = "~/.config/waybar/config"
"waybar/style.css" = "~/.config/waybar/style.css"

[kde]
depends = ["desktop"]
[kde.files]
plasma-workspace = "~/.config/plasma-workspace"
kde = "~/.config"

[vim.files]
LazyVim = { target = "~/.config/LazyVim", type = "symbolic" }
neovide = "~/.config/neovide"

[scripts.files]
bin = "~/.local/bin"

[terminal.files]
wezterm = "~/.config/wezterm"
zellij = "~/.config/zellij"
yazi = { target = "~/.config/yazi", type = "symbolic" }

[git.files]
git-cliff = { target = "~/.config/git-cliff", type = "symbolic" }
gitui = "~/.config/gitui"

[media.files]
zathura = "~/.config/zathura"
mpv = "~/.config/mpv"

[PL.files]
cargo = "~/.cargo"
gdb = "~/.config/gdb"
"pip.conf" = "~/.config/pip/pip.conf"

[font.files]
fontconfig = "~/.config/fontconfig"

[misc.files]
macchina = "~/.config/macchina"
paru = "~/.config/paru"
Templates = { target = "~/Templates", type = "symbolic" }
