#!/usr/bin/env zsh

# XDG
export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME=~/.cache
export XDG_DATA_HOME=~/.local/share
export XDG_STATE_HOME=~/.local/state

# Rust
export RUST_BACKTRACE=1

# NOTE: https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#KDE_Plasma
export XMODIFIERS='@im=fcitx'
if [[ $XDG_SESSION_TYPE == x11 ]] {
    export GTK_IM_MODULE='fcitx'
    export QT_IM_MODULE='fcitx'
    export SDL_IM_MODULE='fcitx'
}

ZDOTDIR=$XDG_CONFIG_HOME/zsh

# 可执行程序目录
typeset -U path # Make unique
path=(
    ~/.cargo/bin
    ~/.local/bin
    $path
    ~/.ghcup/bin
)
